export default {
  BANNER_TEXT:
    "Users are to set their VPN setting when they connect and disconnect to VPN. Priority 3 users must disconnect when the available number of VPN connections goes to or below 3. Those that have been on longest should disconnect first.",
  SERVER_URL: "http://localhost:3001",
  ADMIN_LOGIN_USER_ID: "aaa",
  ADMIN_LOGIN_PASSWORD: "aaa",
  DEFAULT_SELECTED_GROUP: "IT Solution Delivery",
  ANONYMOUS: "anonymous",
  MEMBER_EXISTS_MSG: "Member already exist in the group",
  ADD_MEMBER_LABEL: "Enter member unique name. (Ex: John S)",
  ADMIN_LOGIN_FAILED: "Admin Login Failed",
  DELETE_CONFIRM_MSG: "Are you sure you want to delete ",
  APP_TITLE: "VPN Management",
  TOTAL_VPN_IN_USE: "Total Number of VPNs in Use",
  AVAILABLE_VPNS: "Available VPNs",
  HOME_TITLE: "VPN Management",
  LOGIN_TITLE: "Use anonyomous login or login as admin",
  ANONYMOUS_LOGIN_BUTTON: "Ananymous Login",
  ADMIN_LOGIN_BUTTON: "Login as Admin",
  ADMIN_LOGIN_TITLE: "Enter admin user name and password",
  OK: "OK",
  DELETE: "Delete",
  CANCEL: "Cancel",
  SUBMIT: "Submit",
  LOGIN_ERROR: "Login Error",
  ADD_MEMBER_ERROR: "Error Adding Member",
  ADD_NEW_MEMBER: "Add New Member",
  CONNECTED_USERS: "Connected Users",
  SORT_MEMBERS: "Sort Members",
  DELETE_MODAL_TITLE: "Confirm Delete",
  USER_NAME: "User Name",
  PASSWORD: "Password",
  X: "X",
};
